title: hwanii's blog # your site title
author: GitHub User
email: yth3260@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hwanii.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hwanii # replace with your_github_username or comment to remove link from footer
social:
  name: hwanii
  links:
#    - https://www.facebook.com/ben.balter
#    - https://www.linkedin.com/in/BenBalter
#    - https://plus.google.com/+BenBalter
    - https://github.com/hwanii
#    - https://keybase.io/benbalter

disqus:
  shortname: hwanii # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
#theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
